In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize # カラーバーの描画に用いる
import cartopy.crs as ccrs
import datetime

In [2]:
def dataname(data_month, data_day):
    if data_month < 10 and data_day < 10 :
        dataname = f"0{data_month}0{data_day}"
    if data_month < 10 and data_day >= 10 :
        dataname = f"0{data_month}{data_day}"
    if data_month >= 10 and data_day < 10 :
        dataname = f"{data_month}0{data_day}"
    if data_month >= 10 and data_day >= 10 :
        dataname = f"{data_month}{data_day}"
    print(dataname)
    return(dataname)

In [5]:
draw_year = 2023
draw_month = 6
draw_day = 1

dn = dataname(draw_month, draw_day)

loadfile = f'npz/msm_2023{dn}_s.npz' # 入力ファイル名を定義
dataset = np.load(loadfile) # データセットはまずデータセットごと入力します
dataname_list = dataset.files
print(dataname_list)

data = dataset[dataname_list[1]] # 気象データの代入
lon2 = dataset['lon2'] # 経度(longitude)を変数lon2に保存（2は「2次元配列」の意味）
lat2 = dataset['lat2'] # 緯度(latitude)を変数lat2に保存
y = dataset['y'] # 年(year)を変数yに保存
m = dataset['m'] # 月(month)を変数mに保存
d = dataset['d']
h = dataset['h']

0601
['surface_pressure', 'temperature', 'humidity', 'cloud', 'psea', 'rain1h', 'lon2', 'ueind', 'vwind', 'lat2', 'y', 'm', 'd', 'h']


In [8]:
value_list = np.zeros(0)

for draw_day in range(1,2+1):
    dn = dataname(draw_month, draw_day)
    loadfile = f'npz/msm_2023{dn}_s.npz' # 入力ファイル名を定義
    dataset = np.load(loadfile) # データセットはまずデータセットごと入力します
    dataname_list = dataset.files
    # print(dataname_list)

    data = dataset[dataname_list[7]] # 気象データの代入
    lon2 = dataset['lon2'] # 経度(longitude)を変数lon2に保存（2は「2次元配列」の意味）
    lat2 = dataset['lat2'] # 緯度(latitude)を変数lat2に保存
    y = dataset['y'] # 年(year)を変数yに保存
    m = dataset['m'] # 月(month)を変数mに保存
    d = dataset['d']
    h = dataset['h']

    for i in range(0,24):
        # value = data[392, 80, (y==draw_year)*(m==draw_month)*(d==draw_day)*(h==i)]-273.15
        data2d = (np.squeeze(data[:, :, (y==draw_year)*(m==draw_month)*(d==draw_day)*(h==i)]))
        # value = data2d[(lon2==144.5)*(lat2[392]>43.59)*(lat2[392]<43.61)] #　川湯アメダス付近
        value = data2d[(lon2==144.5)*(lat2>43.55)*(lat2<43.6)] #　網走地方気象台付近
        value_list = np.append(value_list, value)
    
# print(value_list)
pd.Series(value_list).to_csv(f"csv/uwind_43.599998474121094_144.5_20230501-20230531.csv")

0601
0602


In [48]:
data2d = (np.squeeze(data[:, :, (y==draw_year)*(m==draw_month)*(d==draw_day)*(h==0)]))
# value = data2d[(lon2==144.5)*(lat2[392]>43.59)*(lat2[392]<43.61)] #　川湯アメダス付近
value = data2d[(lon2==144.5)*(lat2>43.55)*(lat2<43.6)] #　網走地方気象台付近
value

array([287.95153253])

In [14]:
data2d[(lon2==144.25)*(lat2>43.98)*(lat2<44.02)]

array([53.21101011])

In [17]:
((lon2==144.25)*(lat2>43.98)*(lat2<44.02)).shape

(481, 505)

In [53]:
condition = (lon2==144.5)*(lat2>43.55)*(lat2<43.6)
print(np.unique(lat2[condition]), np.unique(lon2[condition]))
print(lat2[condition][0], lon2[condition][0])

[43.59999847] [144.5]
43.599998474121094 144.5


In [45]:
print(np.unique(lat2[(lon2>=144)*(lon2<=145)*(lat2>=43.50)*(lat2<=43.90)]), np.unique(lon2[(lon2>=144.0)*(lon2<=145)*(lat2>=43.50)*(lat2<=43.90)]))

[43.5        43.54999924 43.59999847 43.65000153 43.70000076 43.75
 43.79999924 43.84999847] [144.     144.0625 144.125  144.1875 144.25   144.3125 144.375  144.4375
 144.5    144.5625 144.625  144.6875 144.75   144.8125 144.875  144.9375
 145.    ]


In [4]:
data.shape

(481, 505, 24)

In [6]:
print(lon2[392])
print(lat2[392])
print(np.where((lat2[392]>43.59)*(lat2[392]<43.61)))

[144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5
 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5
 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5
 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5
 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5
 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5
 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5
 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5
 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5
 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5
 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5
 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5
 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5
 144.5 144.5 144.5 144.5 144.5 144.5 144.5 144.5 14

In [34]:
data[392, 80, (y==draw_year)*(m==draw_month)*(d==draw_day)*(h==0)]-273.15

array([15.21185067])

In [19]:
lon2==144.5

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [21]:
(lon2==144.5).shape

(481, 505)

In [30]:
np.squeeze(data[:, :, (y==draw_year)*(m==draw_month)*(d==draw_day)*(h==0)]-273.15).shape

(481, 505)

In [9]:
(np.squeeze(data[:, :, (y==draw_year)*(m==draw_month)*(d==draw_day)*(h==0)]-273.15))[(lon2==144.5)*(lat2>43.59)*(lat2<43.61)]

array([-224.18898971])

In [49]:
(np.squeeze((lat2[392]>43.98)*(lat2[392]<44.02))).shape

(505,)

In [8]:
lat2[np.squeeze((lat2>43.98)*(lat2<44.02))]

array([44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44.,
       44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44.,
       44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44.,
       44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44.,
       44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44.,
       44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44.,
       44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44.,
       44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44.,
       44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44.,
       44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44.,
       44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44.,
       44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44.,
       44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44.,
       44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44., 44

In [13]:
A = np.array([[1, 2, 3], [4, 2, 5], [7, 4, 9]]) #行列Aを定義する
B = np.array([5,5,4])

In [14]:
B==4

array([False, False,  True])

In [15]:
A[:, B==4]

array([[3],
       [5],
       [9]])